"""Utility helpers shared by :mod:`gal.learning.learn`.

Every function in this module performs one clearly scoped task (file-system
initialisation, event serialization, search-engine setup, etc.) so that the
main learning loop stays focused on the algorithmic steps.  Inline comments
describe the data flow in detail to complement the higher-level narrative in
the Sphinx documentation.
"""

from __future__ import annotations

import csv
import math
import logging
import time
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from gal.search.engine import Search
from gal.search.strategies import get_strategy



def _init_streaming_outputs(exp_dir: Path) -> tuple[csv.writer, Any, Path]:
    """Create the output folders and files used by the learning loop.

    Parameters
    ----------
    exp_dir:
        Root directory for the experiment run.  It is created when absent so
        callers can pass a yet-to-exist path.

    Returns
    -------
    csv_writer, csv_file, q_dir:
        A tuple containing the ``csv.writer`` bound to ``iterations.csv``, the
        open file handle (so the caller can flush/close it), and the directory
        where per-iteration query vectors will be stored as NPZ files.

    Notes
    -----
    The CSV schema is fixed; downstream tooling relies on the field order when
    loading iteration metadata.
    """
    # Ensure the root output directory exists before creating individual files.
    exp_dir.mkdir(parents=True, exist_ok=True)
    # Open the CSV stream in text mode with explicit newline handling so writes
    # remain consistent across platforms.
    it_csv = open(exp_dir / "iterations.csv", "w", newline="", encoding="utf-8")
    csv_writer = csv.writer(it_csv)
    # Emit the header row immediately; the learning loop writes data lines
    # without needing to repeat the schema.
    csv_writer.writerow([
        "iteration_id",
        "query_path",
        "oracle_response",
        "i",
        "j",
        "orientation_score",
        "timestamp_start",
        "timestamp_end",
    ])
    # Queries are stored in a sibling directory, one NPZ file per iteration.
    q_dir = exp_dir / "queries"
    q_dir.mkdir(parents=True, exist_ok=True)
    return csv_writer, it_csv, q_dir


def _ensure_search_engine(engine: Optional[Search], search_strategy: str, X: np.ndarray) -> Search:
    """Return a :class:`Search` instance matching ``search_strategy``.

    Parameters
    ----------
    engine:
        Optional pre-existing :class:`Search` engine; reused when provided so
        experiments can inject custom bounders or strategy state.
    search_strategy:
        Strategy name understood by :func:`gal.search.strategies.get_strategy`.
    X:
        Included for signature parity with historical callers; the array is not
        used here but may be leveraged by downstream extensions.
    """
    if engine is not None:
        return engine
    strat = get_strategy(search_strategy)
    return Search(strategy=strat)


def _log_iteration(
    it: int,
    i: Optional[int],
    j: Optional[int],
    dist: Optional[float],
    radius: float,
    *,
    log_level: int,
    log_every: int,
    exp_dir: Path,
) -> Path:
    """Create the iteration subdirectory and emit debug logs when requested.

    Parameters mirror those recorded in ``iterations.csv`` so the helper can
    output consistent diagnostic messages.
    """
    if it == 0 or (log_level <= logging.DEBUG and (it % log_every == 0)):
        logging.getLogger(__name__).debug(
            "Iter %d: i=%s j=%s dist=%s radius=%.4f",
            it,
            str(i),
            str(j),
            "{:.4f}".format(float(dist)) if dist is not None else "nan",
            float(radius),
        )
    iter_dir = exp_dir / f"iteration_{it:03d}"
    iter_dir.mkdir(parents=True, exist_ok=True)
    return iter_dir


def _export_search_events_npz(path: Path, events: List[Dict[str, Any]]) -> None:
    """Serialize branch-and-bound event traces to an NPZ file.

    Parameters
    ----------
    path:
        Destination NPZ path (typically ``iteration_xxx/search_trace.npz``).
    events:
        List of dictionaries generated by :mod:`gal.search`.  Missing keys are
        defaulted so callers do not need to pre-normalise the records.
    """
    if not events:
        np.savez(
            path,
            event_type=np.array([], dtype=object),
            node_id=np.array([], dtype=np.int64),
            parent_id=np.array([], dtype=np.int64),
            timestamp=np.array([], dtype=float),
            lower_bound=np.array([], dtype=float),
            upper_bound=np.array([], dtype=float),
        )
        return
    # Convert every field to a numpy array once so the archive can be consumed
    # without pandas or h5py.
    ev_type = np.array([str(e.get("event_type", "")) for e in events], dtype=object)
    node_id = np.array([int(e.get("node_id", -1)) for e in events], dtype=np.int64)
    parent_id = np.array([int(e.get("parent_id", -1)) for e in events], dtype=np.int64)
    timestamp = np.array([float(e.get("timestamp", 0.0)) for e in events], dtype=float)
    lower = np.array([float(e.get("lower_bound", np.nan)) for e in events], dtype=float)
    upper = np.array([float(e.get("upper_bound", np.nan)) for e in events], dtype=float)
    np.savez(
        path,
        event_type=ev_type,
        node_id=node_id,
        parent_id=parent_id,
        timestamp=timestamp,
        lower_bound=lower,
        upper_bound=upper,
    )


def _record_query_npz(
    *,
    it: int,
    diff: np.ndarray,
    q_dir: Path,
    csv_writer: csv.writer,
    csv_file: Any,
    y: int,
    i: int,
    j: int,
    t_start: float,
    orientation_score: float | None,
) -> None:
    """Persist the query difference vector and record iteration metadata.

    Parameters mirror the inputs received from :func:`learning_loop`.  The
    helper writes binary data once and keeps the CSV stream flushed so that
    progress can be monitored live during long experiments.
    """
    q_path = q_dir / f"query_{it:03d}.npz"
    np.savez(q_path, vector=np.asarray(diff, dtype=float))
    # Capture the end timestamp as late as possible to approximate wall-clock
    # duration for the iteration.
    t_end = time.time()
    orientation_cell = "" if orientation_score is None or not math.isfinite(orientation_score) else float(orientation_score)
    csv_writer.writerow([
        it,
        f"queries/query_{it:03d}.npz:vector",
        int(y),
        int(i),
        int(j),
        orientation_cell,
        time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(t_start)) + f".{int((t_start%1)*1000):03d}Z",
        time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(t_end)) + f".{int((t_end%1)*1000):03d}Z",
    ])
    csv_file.flush()  # stream stats immediately for long-running experiments


def _save_center_snapshot(iter_dir: Path, center_full: np.ndarray, radius: float, tau: float) -> None:
    """Persist the expanded centre in both ``.npy`` and ``.npz`` formats."""
    np.save(iter_dir / "center_model.npy", center_full)
    try:
        np.savez(
            iter_dir / "center_model.npz",
            center=np.asarray(center_full, dtype=float),
            radius=float(radius),
            tau=float(tau),
        )
    except Exception:
        # Best-effort; keep going even if NPZ fails
        pass


def _finalize_version_space_npz(exp_dir: Path, A: np.ndarray, b: np.ndarray) -> None:
    """Write the terminal version-space matrices to ``final_version_space.npz``."""
    np.savez(
        exp_dir / "final_version_space.npz",
        A=np.asarray(A, dtype=float),
        b=np.asarray(b, dtype=float).reshape(-1, 1),
    )


def _farthest_point_socp(
    A: np.ndarray,
    b: np.ndarray,
    center: np.ndarray,
    *,
    max_directions: int = 64,
    atol: float = 1e-9,
) -> tuple[Optional[np.ndarray], Optional[float]]:
    """Approximate the farthest feasible point by sampling linear programs.

    The routine launches a handful of LPs in different directions (unit basis
    vectors, the current centre, and progressively refined directions) to
    locate a point that maximises the Euclidean distance from ``center`` while
    staying inside ``A x <= b``.  Results are cached so the learning loop can
    guide search orientation when the solve succeeds.

    Returns
    -------
    farthest_point, distance:
        ``farthest_point`` is the maximiser when found, otherwise ``None``.
        ``distance`` is the Euclidean norm between the maximiser and ``center``.
    """

    A_mat = np.asarray(A, dtype=float)
    if A_mat.size == 0:
        logging.getLogger(__name__).debug("Skipping farthest-point search: empty constraint set")
        return None, None

    center_vec = np.asarray(center, dtype=float).reshape(-1)
    if center_vec.size == 0:
        raise ValueError("Center must be a non-empty vector")
    if A_mat.shape[1] != center_vec.size:
        raise ValueError(
            "Constraint matrix column count does not match center dimension: "
            f"{A_mat.shape[1]} vs {center_vec.size}"
        )

    try:
        from scipy.optimize import linprog
    except ImportError:
        logging.getLogger(__name__).warning(
            "scipy not installed; skipping farthest-point computation"
        )
        return None, None

    b_vec = np.asarray(b, dtype=float).reshape(-1)
    dim = center_vec.size
    if dim == 0:
        return None, None

    def _normalize(vec: np.ndarray) -> Optional[np.ndarray]:
        norm = float(np.linalg.norm(vec))
        if norm <= atol:
            return None
        return vec / norm

    unbounded_detected = False

    def _lp(direction: np.ndarray) -> Optional[np.ndarray]:
        nonlocal unbounded_detected
        res = linprog(
            -direction,
            A_ub=A_mat,
            b_ub=b_vec,
            bounds=[(None, None)] * dim,
            method="highs",
        )
        if res.status == 3:
            logging.getLogger(__name__).warning(
                "Farthest-point search encountered an unbounded LP direction"
            )
            unbounded_detected = True
            return None
        if not res.success or res.x is None:
            logging.getLogger(__name__).debug(
                "Farthest-point LP failed (status=%s message=%s)", res.status, res.message
            )
            return None
        return np.asarray(res.x, dtype=float)

    # Seed the queue with canonical basis directions (both signs) so every axis
    # of the polytope is explored at least once.
    initial_dirs: List[np.ndarray] = []
    for idx in range(dim):
        e = np.zeros(dim, dtype=float)
        e[idx] = 1.0
        initial_dirs.append(e)
        initial_dirs.append(-e)
    normalized_center = _normalize(center_vec)
    if normalized_center is not None:
        initial_dirs.append(normalized_center)

    queue: List[np.ndarray] = initial_dirs
    seen: List[np.ndarray] = []
    best_point: Optional[np.ndarray] = None
    best_dist: float = 0.0
    processed = 0

    # Process queued directions breadth-first, tracking how many LPs we solved
    # to enforce the ``max_directions`` cap.
    while queue and processed < max_directions:
        direction = queue.pop(0)
        unit_dir = _normalize(direction)
        if unit_dir is None:
            continue
        # Skip directions that are duplicates (up to sign) of previously solved
        # LPs to avoid redundant work.
        if any(np.allclose(unit_dir, s, atol=1e-8) or np.allclose(unit_dir, -s, atol=1e-8) for s in seen):
            continue
        seen.append(unit_dir)
        candidate = _lp(unit_dir)
        processed += 1
        if candidate is None:
            continue
        # Measure improvement over the current best solution; the ``+ atol``
        # tolerance avoids numerical oscillations when two directions reach the
        # same optimum.
        dist = float(np.linalg.norm(candidate - center_vec))
        if dist <= best_dist + atol:
            continue
        best_point = candidate
        best_dist = dist
        improvement_dir = _normalize(candidate - center_vec)
        if improvement_dir is not None:
            # Revisit the queue with the direction pointing to the best point
            # seen so far; this heuristic captures curved facets of the polytope.
            queue.append(improvement_dir)

    # If no feasible improvement surfaced, signal failure to the caller.
    if best_point is None or best_dist <= atol:
        return None, None

    # Propagate failure when any LP reported an unbounded region.
    if unbounded_detected:
        return None, None

    return best_point, best_dist
